CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    requested_at TIMESTAMP NOT NULL,
    responded_at TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_friendships_recipient FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_friendships_requester_recipient UNIQUE (requester_id, recipient_id),
    CONSTRAINT ck_friendships_distinct_users CHECK (requester_id <> recipient_id)
);

CREATE UNIQUE INDEX uk_friendships_pair ON friendships (
    LEAST(requester_id, recipient_id),
    GREATEST(requester_id, recipient_id)
);

CREATE INDEX idx_friendships_recipient ON friendships(recipient_id);
CREATE INDEX idx_friendships_status ON friendships(status);
